
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://ovmzgamfahnzbayguylc.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bXpnYW1mYWhuemJheWd1eWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjUyNjQsImV4cCI6MjA1OTI0MTI2NH0.la8xT7b4W1T0t9BykrLBtC16m-O88iF82xbUyTRy8xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
